[build]
  base = "Frontend"
  publish = "dist"
  command = "npm ci && npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_API_URL = "https://pulse-ai-stress-management.onrender.com"
  VITE_GEMINI_API_KEY = "AIzaSyCqr9BQafnKOLmmjAtpsTXwtFbXYCMNtXw"

[context.deploy-preview.environment]
  VITE_API_URL = "https://pulse-ai-stress-management.onrender.com"
  VITE_GEMINI_API_KEY = "AIzaSyCqr9BQafnKOLmmjAtpsTXwtFbXYCMNtXw"

[context.branch-deploy.environment]
  VITE_API_URL = "https://pulse-ai-stress-management.onrender.com"
  VITE_GEMINI_API_KEY = "AIzaSyCqr9BQafnKOLmmjAtpsTXwtFbXYCMNtXw"